version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "8081:8081"
    networks:
      - marcosoft-network
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/customerDatabase
    depends_on:
      - mysqldb

  mysqldb:
    image: "mysql:latest"
    restart: always
    ports:
      - 3306:3306
    networks:
      - marcosoft-network
    environment:
      MYSQL_DATABASE: customerDatabase
      MYSQL_ROOT_PASSWORD: mysql
networks:
  marcosoft-network: